### ISSUE TITLE
symfony 6.2 login integration

### ISSUE THREAD

**Issue by mathieu-stadline** [Pixel-Open/cloudflare-turnstile-bundle#2]
Hello,
Is there a simple way to integrate the turnstile in the native login system of symfony 6.2 or do you have to play with the preAuth and do it "manually"?

**Comment by matthieu2607** [comment]
Hi @mathieu-stadline,
I think it is possible to integrate it via the login form.
Do you have a more specific example?

**Comment by ikvasnica** [comment]
Hi @matthieu2607 , I am also having difficulties integrating the widget into a login form. 

It works fine in other custom forms, but when added to a login form (we have a custom `LoginFormType`), the Turnstile validator is never called, thus user is always logged in even though he does not check the checkbox. I think Symfony just never calls custom validators. Is there any recommended solution for this please? 

Code from our login form - this is the same for other forms where it works perfectly fine:
```
use PixelOpen\CloudflareTurnstileBundle\Type\TurnstileType;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\Routing\RouterInterface;

class LoginFormType extends AbstractType
{

    public function buildForm(FormBuilderInterface $builder, array $options): void
    {
        $builder
        // ...
            ->add('security', TurnstileType::class, [
                'attr' => [
                    'data-action' => 'customer-login',
                    'data-theme' => 'light',
                    'data-appearance' => 'interaction-only',
                ],
                'label' => false,
            ])
        // ...
    }

    public function getBlockPrefix(): string
    {
        return '';
    }
```

Thank you.

**Comment by arthurels69** [comment]
Hi @ikvasnica, 
Have you found a solution to your problem? 
I have the same one on working with Sylius, every form works fine except the login one.
